### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ahmedguizani** [marian-margeta/gait-recognition#13]
Hi Marian i was trying to run your code but a warning was shown, i hope that you could help me in resolving this problem, by the way i'm using anaconda for storing the databases and pycharm for python uses.
the warning:

Traceback (most recent call last):
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ../Thesis_solution/models/MPII+LSP.ckpt: Not found: FindFirstFile failed for: ../Thesis_solution/models : The system cannot find the path specified.
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/LORD PARKER/PycharmProjects/nchallafinale/projet.py", line 663, in <module>
    net_pose.restore('../Thesis_solution/models/MPII+LSP.ckpt')
  File "C:/Users/LORD PARKER/PycharmProjects/nchallafinale/projet.py", line 640, in restore
    super()._restore(checkpoint_path, all_vars)
  File "C:/Users/LORD PARKER/PycharmProjects/nchallafinale/projet.py", line 439, in _restore
    saver.restore(self.sess, checkpoint_path)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\training\saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ../Thesis_solution/models/MPII+LSP.ckpt: Not found: FindFirstFile failed for: ../Thesis_solution/models : The system cannot find the path specified.
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "C:/Users/LORD PARKER/PycharmProjects/nchallafinale/projet.py", line 663, in <module>
    net_pose.restore('../Thesis_solution/models/MPII+LSP.ckpt')
  File "C:/Users/LORD PARKER/PycharmProjects/nchallafinale/projet.py", line 640, in restore
    super()._restore(checkpoint_path, all_vars)
  File "C:/Users/LORD PARKER/PycharmProjects/nchallafinale/projet.py", line 438, in _restore
    saver = tf.train.Saver(variables)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\training\saver.py", line 1338, in __init__
    self.build()
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\training\saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\training\saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\training\saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\training\saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\training\saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Users\LORD PARKER\Anaconda\envs\test\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ../Thesis_solution/models/MPII+LSP.ckpt: Not found: FindFirstFile failed for: ../Thesis_solution/models : The system cannot find the path specified.
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Process finished with exit code 1

**Comment by ahmedguizani** [comment]
Hi Marian, i deleted anaconda and i started working just with python but it appears that there are another problem:
File "C:/Users/LORD PARKER/PycharmProjects/untitled9/exemp.py", line 664, in <module>
    net_pose.restore('../Thesis_solution/models/MPII+LSP.ckpt')
File "C:/Users/LORD PARKER/PycharmProjects/untitled9/exemp.py", line 641, in restore
    super()._restore(checkpoint_path, all_vars)
 File "C:/Users/LORD PARKER/PycharmProjects/untitled9/exemp.py", line 440, in _restore
    saver.restore(self.sess, checkpoint_path)
  File "C:\Users\LORD PARKER\PycharmProjects\untitled9\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1715, in restore
    if not checkpoint_exists(compat.as_text(save_path)):
  File "C:\Users\LORD PARKER\PycharmProjects\untitled9\venv\lib\site-packages\tensorflow\python\training\saver.py", line 2056, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "C:\Users\LORD PARKER\PycharmProjects\untitled9\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "C:\Users\LORD PARKER\PycharmProjects\untitled9\venv\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: ../Thesis_solution/models : The system cannot find the path specified.
; No such process

**Comment by ahmedguizani** [comment]
could you please help me for this issues. i need to see how based on a database of normal gait (based on deep learning) we could detect a suspicious human behaviours.
Best regards.

**Comment by ahmedguizani** [comment]
no result until now hopefully you gonna see my messages.
